{{- if and .Values.app.metrics.service.enabled .Values.app.metrics.service.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vault-issuer.name" . }}
  namespace: {{ include "vault-issuer.namespace" . }}
  labels:
    app: {{ include "vault-issuer.name" . }}
    {{- include "vault-issuer.labels" . | nindent 4 }}
    prometheus: {{ .Values.app.metrics.service.servicemonitor.prometheusInstance }}
    {{- with .Values.app.metrics.service.servicemonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ include "vault-issuer.name" . }}
  selector:
    matchLabels:
      app: {{ include "vault-issuer.name" . }}
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - {{ include "vault-issuer.namespace" . }}
  endpoints:
  - targetPort: {{ .Values.app.metrics.port }}
    path: "/metrics"
    interval: {{ .Values.app.metrics.service.servicemonitor.interval }}
    scrapeTimeout: {{ .Values.app.metrics.service.servicemonitor.scrapeTimeout }}
    {{- with .Values.app.metrics.service.servicemonitor.endpointAdditionalProperties }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
